"""Runtime validation smoke test tool for the connected FLAC bridge."""

from __future__ import annotations

import json
from typing import Any

from fastmcp import FastMCP
from pydantic import Field

from flac_mcp.bridge import get_bridge_client
from flac_mcp.contracts import build_ok
from flac_mcp.formatting import build_bridge_error, build_operation_error, is_bridge_connectivity_error

_RUNTIME_VALIDATION_TEMPLATE = r"""
# FLAC_MCP_RUNTIME_VALIDATION
import json
import os
import platform
import re
import sys
import tempfile
import traceback

import itasca as it

include_file_write = __INCLUDE_FILE_WRITE__
keep_artifacts = __KEEP_ARTIFACTS__
include_model_reset = __INCLUDE_MODEL_RESET__

checks = []
artifacts = {}
runtime = {}


def add_check(name, ok, details=None, error=None):
    item = {"name": name, "ok": bool(ok)}
    if details is not None:
        item["details"] = details
    if error:
        item["error"] = str(error)
    checks.append(item)


def detect_runtime():
    executable = getattr(sys, "executable", "") or ""
    exe_lower = executable.lower()

    product = "unknown"
    if "flac3d" in exe_lower or "flac3" in exe_lower:
        product = "flac3d"
    elif "flac2d" in exe_lower or "flac2" in exe_lower:
        product = "flac2d"

    version = None
    match = re.search(r"(?:flac(?:2d|3d)?|itascasoftware)(\d)(\d{2})", exe_lower)
    if match:
        version = "%s.%s" % (match.group(1), match.group(2).lstrip("0") or "0")
    else:
        match = re.search(r"flac(?:2d|3d)?(?P<major>[679])(?:[_\-.]|$)", exe_lower)
        if match:
            version = "%s.0" % match.group("major")

    dim = it.dim()
    if dim == 2 and product == "unknown":
        product = "flac2d"
    elif dim == 3 and product == "unknown":
        product = "flac3d"

    return {
        "product": product,
        "dimension": dim,
        "flac_version": version,
        "python_version": sys.version.split()[0],
        "python_executable": executable,
        "platform": platform.platform(),
    }


try:
    runtime = detect_runtime()
    add_check(
        "runtime_identity",
        runtime.get("dimension") in (2, 3) and runtime.get("product") in ("flac2d", "flac3d"),
        runtime,
    )
except Exception as exc:
    add_check("runtime_identity", False, error="%s\n%s" % (exc, traceback.format_exc()))

try:
    output = it.command("model list information")
    add_check(
        "command_execution",
        True,
        {
            "command": "model list information",
            "output_type": type(output).__name__,
        },
    )
except Exception as exc:
    add_check("command_execution", False, {"command": "model list information"}, "%s\n%s" % (exc, traceback.format_exc()))

if include_file_write:
    dat_path = None
    try:
        base_dirs = [os.getcwd(), tempfile.gettempdir()]
        base_dir = next((path for path in base_dirs if path and os.path.isdir(path)), tempfile.gettempdir())
        dat_path = os.path.abspath(os.path.join(base_dir, "flac_mcp_runtime_validation.dat"))
        content = "; generated by flac-mcp runtime validation\nmodel list information\n"
        with open(dat_path, "w", encoding="utf-8") as handle:
            handle.write(content)
        with open(dat_path, "r", encoding="utf-8") as handle:
            read_back = handle.read()
        if not keep_artifacts:
            os.remove(dat_path)
        artifacts["dat_file"] = {
            "path": dat_path,
            "kept": bool(keep_artifacts),
            "removed": not keep_artifacts,
        }
        add_check(
            "dat_file_write",
            read_back == content,
            {"path": dat_path, "kept": bool(keep_artifacts), "removed": not keep_artifacts},
        )
    except Exception as exc:
        details = {"path": dat_path} if dat_path else None
        add_check("dat_file_write", False, details, "%s\n%s" % (exc, traceback.format_exc()))

if include_model_reset:
    try:
        it.command("model new")
        it.command("model list information")
        add_check(
            "model_reset_smoke",
            True,
            {
                "commands": ["model new", "model list information"],
                "destructive": True,
            },
        )
    except Exception as exc:
        add_check(
            "model_reset_smoke",
            False,
            {"commands": ["model new", "model list information"], "destructive": True},
            "%s\n%s" % (exc, traceback.format_exc()),
        )

passed = sum(1 for item in checks if item.get("ok"))
failed = len(checks) - passed
validation = {
    "summary": {
        "status": "passed" if failed == 0 else "failed",
        "passed": passed,
        "failed": failed,
        "total": len(checks),
        "destructive_checks_enabled": bool(include_model_reset),
    },
    "runtime": runtime,
    "checks": checks,
    "artifacts": artifacts,
}

print("FLAC_MCP_RUNTIME_VALIDATION " + json.dumps(validation, sort_keys=True))
result = validation
"""


def _validation_code(
    *,
    include_file_write: bool,
    keep_artifacts: bool,
    include_model_reset: bool,
) -> str:
    return (
        _RUNTIME_VALIDATION_TEMPLATE.replace("__INCLUDE_FILE_WRITE__", repr(include_file_write))
        .replace("__KEEP_ARTIFACTS__", repr(keep_artifacts))
        .replace("__INCLUDE_MODEL_RESET__", repr(include_model_reset))
    )


def _parse_validation_response(response: dict[str, Any]) -> dict[str, Any] | None:
    data = response.get("data") or {}
    result = data.get("result")
    if isinstance(result, dict) and isinstance(result.get("summary"), dict):
        return result

    output = data.get("output") or ""
    for line in reversed(output.strip().splitlines()):
        marker = "FLAC_MCP_RUNTIME_VALIDATION "
        if line.startswith(marker):
            parsed = json.loads(line[len(marker) :])
            if isinstance(parsed, dict):
                return parsed
    return None


def register(mcp: FastMCP) -> None:
    """Register flac_validate_runtime tool."""

    @mcp.tool()
    async def flac_validate_runtime(
        include_file_write: bool = Field(
            True,
            description="Create, read, and remove a small temporary .dat file from the FLAC process.",
        ),
        keep_artifacts: bool = Field(
            False,
            description="Keep the generated validation .dat file instead of deleting it. Only applies to file checks.",
        ),
        include_model_reset: bool = Field(
            False,
            description=(
                "Run a destructive model-reset smoke check using 'model new'. "
                "Default is false to avoid modifying the active model."
            ),
        ),
        timeout: int = Field(
            20,
            ge=1,
            le=600,
            description="Validation execution timeout in seconds.",
        ),
    ) -> dict[str, Any]:
        """Run a runtime smoke validation against the connected FLAC process.

        The default validation is non-destructive: it checks bridge execution,
        runtime identity, safe command execution, and temporary `.dat` file
        write/read/delete behavior. Enable `include_model_reset` only when it
        is acceptable to run `model new` in the active FLAC session.
        """
        try:
            client = await get_bridge_client()
            response = await client.execute_code(
                _validation_code(
                    include_file_write=include_file_write,
                    keep_artifacts=keep_artifacts,
                    include_model_reset=include_model_reset,
                ),
                timeout_ms=timeout * 1000,
            )
        except Exception as exc:
            if is_bridge_connectivity_error(exc):
                return build_bridge_error(exc)
            return build_operation_error("runtime_validation_failed", "Runtime validation failed", reason=str(exc))

        status = response.get("status", "unknown")
        if status not in {"success", "completed", "ok"}:
            data = response.get("data") or {}
            return build_operation_error(
                str(status or "runtime_validation_failed"),
                "Runtime validation failed",
                reason=str(response.get("message") or ""),
                output=data.get("output") or None,
            )

        try:
            parsed = _parse_validation_response(response)
        except Exception as exc:
            data = response.get("data") or {}
            return build_operation_error(
                "runtime_validation_parse_failed",
                "Runtime validation returned an unrecognized payload",
                reason=str(exc),
                output=data.get("output") or None,
            )

        if parsed is None:
            data = response.get("data") or {}
            return build_operation_error(
                "runtime_validation_parse_failed",
                "Runtime validation returned no structured result",
                output=data.get("output") or None,
            )

        return build_ok(parsed)
