"""Validate a live FLAC bridge runtime without adding an MCP tool."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from typing import Any

from flac_mcp.bridge import close_bridge_client, get_bridge_client

RUNTIME_VALIDATION_TEMPLATE = r"""
# FLAC_MCP_RUNTIME_VALIDATION
import json
import os
import platform
import re
import sys
import tempfile
import traceback

import itasca as it

include_file_write = __INCLUDE_FILE_WRITE__
keep_artifacts = __KEEP_ARTIFACTS__
include_model_reset = __INCLUDE_MODEL_RESET__

checks = []
artifacts = {}
runtime = {}


def add_check(name, ok, details=None, error=None):
    item = {"name": name, "ok": bool(ok)}
    if details is not None:
        item["details"] = details
    if error:
        item["error"] = str(error)
    checks.append(item)


def detect_runtime():
    executable = getattr(sys, "executable", "") or ""
    exe_lower = executable.lower()

    product = "unknown"
    if "flac3d" in exe_lower or "flac3" in exe_lower:
        product = "flac3d"
    elif "flac2d" in exe_lower or "flac2" in exe_lower:
        product = "flac2d"

    version = None
    match = re.search(r"(?:flac(?:2d|3d)?|itascasoftware)(\d)(\d{2})", exe_lower)
    if match:
        version = "%s.%s" % (match.group(1), match.group(2).lstrip("0") or "0")
    else:
        match = re.search(r"flac(?:2d|3d)?(?P<major>[679])(?:[_\-.]|$)", exe_lower)
        if match:
            version = "%s.0" % match.group("major")

    dim = it.dim()
    if dim == 2 and product == "unknown":
        product = "flac2d"
    elif dim == 3 and product == "unknown":
        product = "flac3d"

    return {
        "product": product,
        "dimension": dim,
        "flac_version": version,
        "python_version": sys.version.split()[0],
        "python_executable": executable,
        "platform": platform.platform(),
    }


try:
    runtime = detect_runtime()
    add_check(
        "runtime_identity",
        runtime.get("dimension") in (2, 3) and runtime.get("product") in ("flac2d", "flac3d"),
        runtime,
    )
except Exception as exc:
    add_check("runtime_identity", False, error="%s\n%s" % (exc, traceback.format_exc()))

try:
    output = it.command("model list information")
    add_check(
        "command_execution",
        True,
        {
            "command": "model list information",
            "output_type": type(output).__name__,
        },
    )
except Exception as exc:
    add_check("command_execution", False, {"command": "model list information"}, "%s\n%s" % (exc, traceback.format_exc()))

if include_file_write:
    dat_path = None
    try:
        base_dirs = [os.getcwd(), tempfile.gettempdir()]
        base_dir = next((path for path in base_dirs if path and os.path.isdir(path)), tempfile.gettempdir())
        dat_path = os.path.abspath(os.path.join(base_dir, "flac_mcp_runtime_validation.dat"))
        content = "; generated by flac-mcp runtime validation\nmodel list information\n"
        with open(dat_path, "w", encoding="utf-8") as handle:
            handle.write(content)
        with open(dat_path, "r", encoding="utf-8") as handle:
            read_back = handle.read()
        if not keep_artifacts:
            os.remove(dat_path)
        artifacts["dat_file"] = {
            "path": dat_path,
            "kept": bool(keep_artifacts),
            "removed": not keep_artifacts,
        }
        add_check(
            "dat_file_write",
            read_back == content,
            {"path": dat_path, "kept": bool(keep_artifacts), "removed": not keep_artifacts},
        )
    except Exception as exc:
        details = {"path": dat_path} if dat_path else None
        add_check("dat_file_write", False, details, "%s\n%s" % (exc, traceback.format_exc()))

if include_model_reset:
    try:
        it.command("model new")
        it.command("model list information")
        add_check(
            "model_reset_smoke",
            True,
            {
                "commands": ["model new", "model list information"],
                "destructive": True,
            },
        )
    except Exception as exc:
        add_check(
            "model_reset_smoke",
            False,
            {"commands": ["model new", "model list information"], "destructive": True},
            "%s\n%s" % (exc, traceback.format_exc()),
        )

passed = sum(1 for item in checks if item.get("ok"))
failed = len(checks) - passed
validation = {
    "summary": {
        "status": "passed" if failed == 0 else "failed",
        "passed": passed,
        "failed": failed,
        "total": len(checks),
        "destructive_checks_enabled": bool(include_model_reset),
    },
    "runtime": runtime,
    "checks": checks,
    "artifacts": artifacts,
}

print("FLAC_MCP_RUNTIME_VALIDATION " + json.dumps(validation, sort_keys=True))
result = validation
"""


def validation_code(*, include_file_write: bool, keep_artifacts: bool, include_model_reset: bool) -> str:
    return (
        RUNTIME_VALIDATION_TEMPLATE.replace("__INCLUDE_FILE_WRITE__", repr(include_file_write))
        .replace("__KEEP_ARTIFACTS__", repr(keep_artifacts))
        .replace("__INCLUDE_MODEL_RESET__", repr(include_model_reset))
    )


def parse_validation_response(response: dict[str, Any]) -> dict[str, Any] | None:
    data = response.get("data") or {}
    result = data.get("result")
    if isinstance(result, dict) and isinstance(result.get("summary"), dict):
        return result

    output = data.get("output") or ""
    marker = "FLAC_MCP_RUNTIME_VALIDATION "
    for line in reversed(output.strip().splitlines()):
        if line.startswith(marker):
            parsed = json.loads(line[len(marker) :])
            if isinstance(parsed, dict):
                return parsed
    return None


def print_human_report(validation: dict[str, Any]) -> None:
    summary = validation.get("summary") or {}
    runtime = validation.get("runtime") or {}
    print("FLAC runtime validation:", summary.get("status", "unknown"))
    print(
        "Runtime:",
        runtime.get("product", "unknown"),
        runtime.get("flac_version", "unknown"),
        "dimension",
        runtime.get("dimension", "unknown"),
    )
    print("Checks: {passed}/{total} passed".format(**summary))
    for check in validation.get("checks") or []:
        prefix = "PASS" if check.get("ok") else "FAIL"
        print(f"- {prefix} {check.get('name')}")
        if check.get("error"):
            print(f"  {check['error']}")


async def run_validation(args: argparse.Namespace) -> int:
    if args.bridge_url:
        os.environ["FLAC_MCP_BRIDGE_URL"] = args.bridge_url

    try:
        client = await get_bridge_client()
        response = await client.execute_code(
            validation_code(
                include_file_write=args.include_file_write,
                keep_artifacts=args.keep_artifacts,
                include_model_reset=args.include_model_reset,
            ),
            timeout_ms=args.timeout * 1000,
        )
    finally:
        await close_bridge_client()

    status = response.get("status")
    if status not in {"success", "completed", "ok"}:
        print(json.dumps({"ok": False, "response": response}, indent=2, sort_keys=True), file=sys.stderr)
        return 2

    validation = parse_validation_response(response)
    if validation is None:
        print(json.dumps({"ok": False, "error": "validation payload not found", "response": response}, indent=2), file=sys.stderr)
        return 2

    if args.json:
        print(json.dumps(validation, indent=2, sort_keys=True))
    else:
        print_human_report(validation)

    summary = validation.get("summary") or {}
    return 0 if summary.get("failed") == 0 else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate a live FLAC bridge runtime.")
    parser.add_argument("--bridge-url", help="Bridge URL. Defaults to FLAC_MCP_BRIDGE_URL or ws://localhost:9002.")
    parser.add_argument("--timeout", type=int, default=20, help="Validation timeout in seconds.")
    parser.add_argument("--json", action="store_true", help="Print the structured validation payload.")
    parser.add_argument(
        "--no-file-write",
        dest="include_file_write",
        action="store_false",
        help="Skip the temporary .dat write/read/delete check.",
    )
    parser.add_argument(
        "--keep-artifacts",
        action="store_true",
        help="Keep generated validation files instead of deleting them.",
    )
    parser.add_argument(
        "--include-model-reset",
        action="store_true",
        help="Run a destructive smoke check with 'model new'.",
    )
    parser.set_defaults(include_file_write=True)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return asyncio.run(run_validation(args))


if __name__ == "__main__":
    raise SystemExit(main())
